# Generated by Django 4.0.4 on 2022-05-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_id_back_client_id_front_alter_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
    ]
