# Generated by Django 4.0.4 on 2022-05-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_client_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('sender_id', models.CharField(max_length=200)),
                ('receiver_id', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('sender_photo', models.CharField(max_length=200)),
                ('receiver_photo', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=200)),
            ],
        ),
    ]
