# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_apptransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptransactions',
            name='day',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='apptransactions',
            name='lat',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='apptransactions',
            name='lng',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='apptransactions',
            name='month',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='apptransactions',
            name='time',
            field=models.CharField(default='1:00', max_length=200),
        ),
    ]
