# Generated by Django 4.0.4 on 2022-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_apptransactions_day_apptransactions_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('reported_at', models.CharField(max_length=200)),
                ('reporter', models.CharField(max_length=200)),
                ('reported', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('lng', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='apptransactions',
            name='time',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
