# Generated by Django 4.0.4 on 2022-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reportedtransactions_alter_apptransactions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedtransactions',
            name='transaction_id',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
